---
- name: Installer Apache et afficher les informations du serveur
  hosts: all
  become: yes  # Utilisez sudo pour obtenir des privilèges d'administrateur
  tasks:
    - name: Installer Apache2
      apt:
        name: apache2
        state: present
      notify: 
        - Démarrer Apache

    - name: Déployer la page html
      template:
        src: index.html.j2
        dest: /var/www/html/index.html

    - name: Déployer la page css
      copy:
        src: styles.css
        dest: /var/www/html/

  handlers:
    - name: Démarrer Apache
      service:
        name: apache2
        state: started
